version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy --template-file template.yml --parameter-overrides EnvironmentName=Udagram --stack-name mystack1
workflows:
  my_workflow:
    jobs:
      - create_infrastructure